In [4]:
import pandas as pd

In [8]:
sales = pd.read_csv('Auto_Sales_data.csv', index_col = 0)

In [16]:
sales_modified = sales.drop(['ORDERLINENUMBER','CUSTOMERNAME','PHONE','ADDRESSLINE1','POSTALCODE','CONTACTLASTNAME','CONTACTFIRSTNAME'], axis=1)

In [18]:
sales_modified.head()

,QUANTITYORDERED,PRICEEACH,SALES,ORDERDATE,DAYS_SINCE_LASTORDER,STATUS,PRODUCTLINE,MSRP,PRODUCTCODE,CITY,COUNTRY,DEALSIZE
ORDERNUMBER,,,,,,,,,,,,
10107,30,95.70,2871.00,24/02/2018,828,Shipped,Motorcycles,95,S10_1678,NYC,USA,Small
10121,34,81.35,2765.90,07/05/2018,757,Shipped,Motorcycles,95,S10_1678,Reims,France,Small
10134,41,94.74,3884.34,01/07/2018,703,Shipped,Motorcycles,95,S10_1678,Paris,France,Medium
10145,45,83.26,3746.70,25/08/2018,649,Shipped,Motorcycles,95,S10_1678,Pasadena,USA,Medium
10168,36,96.66,3479.76,28/10/2018,586,Shipped,Motorcycles,95,S10_1678,Burlingame,USA,Medium

In [31]:
print(sales_modified.notnull().sum())

QUANTITYORDERED         2747
PRICEEACH               2747
SALES                   2747
ORDERDATE               2747
DAYS_SINCE_LASTORDER    2747
STATUS                  2747
PRODUCTLINE             2747
MSRP                    2747
PRODUCTCODE             2747
CITY                    2747
COUNTRY                 2747
DEALSIZE                2747
dtype: int64

In [23]:
print(sales_modified.columns.tolist())

['QUANTITYORDERED', 'PRICEEACH', 'SALES', 'ORDERDATE', 'DAYS_SINCE_LASTORDER', 'STATUS', 'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CITY', 'COUNTRY', 'DEALSIZE']

In [25]:
indicater = pd.read_csv('e22f2293-f590-46c3-91df-5eea2aeed022_Data.csv', index_col = 0)

In [27]:
indicater.head()

,Country Code,Series Name,Series Code,2018 [YR2018],2019 [YR2019],2020 [YR2020]
Country Name,,,,,,
Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,31.4,32.6,33.8
Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,14.5,15.6,16.4
Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,82.6,83.2,83.8
Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,93.4,97.7,97.7
Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,91.6,97.1,97.1

In [29]:
indicater.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401399 entries, Afghanistan to Last Updated: 04/15/2025
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Country Code   401394 non-null  object
 1   Series Name    401394 non-null  object
 2   Series Code    401394 non-null  object
 3   2018 [YR2018]  401394 non-null  object
 4   2019 [YR2019]  401394 non-null  object
 5   2020 [YR2020]  401394 non-null  object
dtypes: object(6)
memory usage: 21.4+ MB

In [33]:
print(indicater.columns.tolist())

['Country Code', 'Series Name', 'Series Code', '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]']